// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: healthcheck.sql

package db

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT NOW()
`

func (q *Queries) Ping(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, ping)
	var now interface{}
	err := row.Scan(&now)
	return now, err
}
